---
- name: create monitoring path
  file:
    path: "{{ monitoring_gfs_path }}"
    state: directory
    owner: "{{ docker_user }}"
    group: docker
    mode: 0755

- name: copy docker-compose
  template:
    src: "docker-compose.yml"
    dest: "{{ monitoring_gfs_path }}"
    owner: "{{ docker_user }}"
    group: docker
    mode: 0644
    force: yes

- name: run compose
  shell: "docker stack deploy -c {{ monitoring_gfs_path }}/docker-compose.yml --with-registry-auth --prune monitoring"
