---
- name: create monitoring paths
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_user }}"
    group: docker
    mode: 0755
  with_items:
    - "{{ monitoring_gfs_path }}/gluster_exporter"
    - "{{ monitoring_gfs_path }}/gluster_exporter/config"

- name: copy monitoring configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ docker_user }}"
    group: docker
    mode: 0644
    force: yes
  loop:
    - { src: "docker-compose.yml", dest: "{{ monitoring_gfs_path }}" }
    - { src: "gluster-exporter.toml", dest: "{{ monitoring_gfs_path }}/gluster_exporter/config" }

- name: run compose
  shell: "docker stack deploy -c {{ monitoring_gfs_path }}/docker-compose.yml --with-registry-auth --prune monitoring"
