---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    {{ lookup('template', '../../nms_stack/nms_cli/nms_stack/roles/stats/templates/alertmanager.yml') | indent(width=4, indentfirst=False )}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    {{ lookup('template', '../../nms_stack/nms_cli/nms_stack/roles/stats/templates/prometheus.yml') | indent(width=4, indentfirst=False )}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cache-env
data:
  PROMETHEUS_CACHE_LIMIT: "1000000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configurer-env
data:
  PROM_ALERTCONFIG_PORT: "9100"
  RULES_DIR: /etc/configs/alert_rules
  PROMETHEUS_URL: prometheus:9090
  ALERTMANAGER_CONFIG_PORT: "9101"
  ALERTMANAGER_CONF_PATH: /etc/prometheus/alertmanager.yml
  ALERTMANAGER_URL: alertmanager:9093
  MULTITENANT: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stats-env
data:
  HTTP_THREADS: "8"
  KAFKA_BROKER_LIST: PLAINTEXT://kafka:9092
  KAFKA_STATS_ENABLED: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
  - port: 3306
  selector:
    app: prometheus
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
      imagePullSecrets:
        - name: tg-repo-creds
      containers:
      - image: prom/prometheus
        name: prometheus
        args: ["--config.file=/etc/prometheus/prometheus.yml",
                  "--storage.tsdb.path=/prometheus",
                  "--web.console.libraries=/usr/share/prometheus/console_libraries",
                  "--web.console.templates=/usr/share/prometheus/consoles",
                  "--web.external-url=https://prometheus/prometheus/",
                  "--web.route-prefix=/",
                  "--web.enable-lifecycle"]
        volumeMounts:
          - name: prometheus-config
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
      - image: secure.cxl-terragraph.com:443/prometheus_cache:stable
        name: prometheus-cache
        command: ["/bin/sh", "-c", "/bin/prometheus-cache -limit=$${PROMETHEUS_CACHE_LIMIT}"]
        envFrom:
          - configMapRef:
              name: prometheus-cache-env
      - image: prom/alertmanager
        name: alertmanager
        args: ["--config.file=/etc/prometheus/alertmanager.yml"]
        envFrom:
          - configMapRef:
              name: prometheus-cache-env
        volumeMounts:
          - name: prometheus-config
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
          - name: alertmanager-config
            mountPath: /etc/prometheus/alertmanager.yml
            subPath: alertmanager.yml
      - image: facebookincubator/prometheus-configurer:1.0.0
        name: prometheus-configurer
        args: ['-port=9100' ,
            '-rules-dir=/etc/configs/alert_rules',
            '-prometheusURL=stats_prometheus:9090',
            '-multitenant-label=networkID']
        volumeMounts:
          - name: prometheus-config
            mountPath: /etc/configs/prometheus.yml
            subPath: prometheus.yml
          - name: alertmanager-config
            mountPath: /etc/configs/alertmanager.yml
            subPath: alertmanager.yml
      - image: facebookincubator/alertmanager-configurer:1.0.0
        name: alertmanager-configurer
        args: ['-port=9101',
            '-alertmanager-conf=/etc/configs/alertmanager.yml',
            '-alertmanagerURL=stats_alertmanager:9093',
            '-multitenant-label=networkID']
        volumeMounts:
          - name: prometheus-config
            mountPath: /etc/configs/prometheus.yml
            subPath: prometheus.yml
          - name: alertmanager-config
            mountPath: /etc/configs/alertmanager.yml
            subPath: alertmanager.yml
