{{- if .Values.databaseCreate }}
apiVersion: v1
kind: Secret
metadata:
  {{- with .Values.tgnms.database.service }}
  name: {{ .name }}
  labels:
    app: {{ .name }}
  {{- end }}
type: Opaque
data:
  {{- with .Values.tgnms.database.env }}
  host: {{ .host | b64enc }}
  rootUser: {{ .rootUser | b64enc }}
  rootPass: {{ .rootPass | b64enc }}
  dbName: {{ .dbName | b64enc }}
  dbUser: {{ .dbUser | b64enc }}
  dbPass: {{ .dbPass | b64enc }}
  {{- end }}
{{- end }}
