apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
  - name: transport
    port: 9300

---
apiVersion: v1
kind: Service
metadata:
  name: es-loadbalancer
spec:
  selector:
    app: elasticsearch
  ports:
  - name: http
    port: 80
    targetPort: 9200
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ elasticsearch_size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/es-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ elasticsearch_size }}
---
# Jinja has no list comprehensions so use this ugly thing instead
{% set master_nodes = [] %}
{% for i in range(3) %}
{% set _ = master_nodes.append('esnode-{}'.format(i)) %}
{% endfor %}
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
data:
  elasticsearch.yml: |
    cluster.name: my-elastic-cluster
    cluster.initial_master_nodes: {{ ",".join(master_nodes) }}
    network.host: "_eth0:ipv6_"
    bootstrap.memory_lock: false
    discovery.zen.ping.unicast.hosts: elasticsearch
    discovery.zen.minimum_master_nodes: 1
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
  ES_JAVA_OPTS: -Xms512m -Xmx512m
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esnode
spec:
  serviceName: es
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
      containers:
      - name: es
        resources:
            requests:
                memory: 1Gi
        securityContext:
          privileged: true
          runAsUser: 0
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        image: {{ elasticsearch_image }}
        imagePullPolicy: {{ image_pull_policy }}
        env:
        - name: ES_JAVA_OPTS
          valueFrom:
              configMapKeyRef:
                  name: es-config
                  key: ES_JAVA_OPTS
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
        ports:
        - containerPort: 9200
          name: es-http
        - containerPort: 9300
          name: es-transport
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
        - name: es-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-pv-claim
        - name: es-config
          configMap:
            name: es-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  init-elasticsearch-config
data:
  init_elasticsearch.sh: |
    {{ lookup('template', '../../../nms_stack/nms_cli/nms_stack/roles/efk/files/init_elasticsearch.sh') | indent(width=4, indentfirst=False )}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-elasticsearch
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      volumes:
        - name: init-elasticsearch-config
          configMap:
            name: init-elasticsearch-config
      containers:
      - name: init-elasticsearch
        image: curlimages/curl:7.72.0
        command: ["/bin/sh", "/tmp/init_elasticsearch.sh"]
        volumeMounts:
          - name: init-elasticsearch-config
            mountPath: /tmp/init_elasticsearch.sh
            subPath: init_elasticsearch.sh
      restartPolicy: Never
  backoffLimit: 4
