---
- name: Download and install GlusterFS gpg key
  shell: "curl -sSL 'https://download.gluster.org/pub/gluster/glusterfs/7/rsa.pub' | apt-key add -"
  environment:
    https_proxy: "{{ https_proxy }}"

- name: Ensure PPA for GlusterFS is present.
  apt_repository:
    repo: "deb http://ppa.launchpad.net/gluster/glusterfs-7/ubuntu {{ ansible_distribution_release }} main"
    state: present
    update_cache: true
  register: glusterfs_ppa_added
  when: glusterfs_ppa_use

- name: Ensure GlusterFS will reinstall if the PPA was just added.
  apt:
    name:
      - glusterfs-server
      - glusterfs-client
    state: absent
  when: glusterfs_ppa_added.changed
  tags: ['skip_ansible_lint']

- name: Ensure GlusterFS is installed.
  apt:
    name:
      - glusterfs-server
      - glusterfs-client
    state: present
    default_release: "{{ glusterfs_default_release }}"
