---
- name: Download and install GlusterFS gpg key
  shell: "curl -sSL 'https://download.gluster.org/pub/gluster/glusterfs/7/rsa.pub' | apt-key add -"
  environment:
    https_proxy: "{{ https_proxy }}"

- name: Ensure PPA for GlusterFS is present.
  register: glusterfs_ppa_added
  shell: sudo add-apt-repository -y ppa:gluster/glusterfs-7 && sudo apt update

- name: Ensure GlusterFS will reinstall if the PPA was just added.
  apt:
    name:
      - glusterfs-server
      - glusterfs-client
    state: absent
  when: glusterfs_ppa_added.changed
  tags: ['skip_ansible_lint']

- name: Ensure GlusterFS is installed.
  apt:
    name:
      - glusterfs-server
      - glusterfs-client
    state: present
    default_release: "{{ glusterfs_default_release }}"
