---
{% if dockerconfig is defined and dockerconfig != None %}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ namespace }}
  name: tg-repo-creds
data:
  # base64 of a .docker/config.json with creds for secure.cxl-terragraph.com:443
  .dockerconfigjson: {{ dockerconfig }}
type: kubernetes.io/dockerconfigjson
{% endif %}
