apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ namespace }}
  name: init-sql-config
data:
  service.sql: |
    {{ lookup('template', '../database/service.sql') | indent(width=4, indentfirst=False )}}
