apiVersion: v1
kind: Service
metadata:
  namespace: "{{ namespace }}"
  name: docs
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: docs
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "{{ namespace }}"
  name: docs
spec:
  selector:
    matchLabels:
      app: docs
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: "{{ namespace }}"
      labels:
        app: docs
    spec:
      containers:
      - image: {{ docs_image }}
        imagePullPolicy: "{{ image_pull_policy }}"
        name: docs
      imagePullSecrets:
        - name: tg-repo-creds
