- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Install docker, kubectl, and kubeadm for Ubuntu
  include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install docker, kubectl, and kubeadm for RHEL
  include: rhel.yml
  when: ansible_os_family == "RedHat"
