---
- name: create msa paths
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_user }}"
    group: docker
    mode: 0755
  loop:
    - "{{ msa_gfs_path }}/config"
    - "{{ msa_gfs_path }}/scripts"
    - "{{ msa_gfs_path }}/env"

- name: copy msa configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ docker_user }}"
    group: docker
    mode: 0644
    force: yes
  loop:
    - { src: "docker-compose.yml", dest: "{{ msa_gfs_path }}" }
    - { src: "config.json", dest: "{{ msa_gfs_path }}/config" }

- name: copy scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ docker_user }}"
    group: docker
    mode: 0755
    force: yes
  loop:
    - { src: "scripts/create_msa_database.sh", dest: "{{ msa_gfs_path }}/scripts"}
    - { src: "scripts/msa.sql", dest: "{{ msa_gfs_path }}/scripts"}

- name: establish services
  include_tasks:
    file: service.yml
  with_items:
    - { name: "analytics", has_database: false }
    - { name: "default_routes_service", has_database: true }
    - { name: "topology_service", has_database: true }
    - { name: "weather_service", has_database: false }
  loop_control:
    loop_var: service

- name: run compose
  shell: "docker stack deploy -c {{ msa_gfs_path }}/docker-compose.yml --with-registry-auth msa"

- name: remove weather service (weather_service_openweathermap_api_key not provided)
  # The weather service should not be started if there is no API key provided,
  # so if it is missing scale it down to 0
  shell: "docker service update --replicas=0 msa_weather_service"
  when: weather_service_openweathermap_api_key is not defined

- name: clean compose
  file:
    path: "{{ msa_gfs_path }}/docker-compose.yml"
    state: absent
  when: not dev_mode
