---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "{{ namespace }}"
  name: chihaya-config
data:
  chihaya.yml: |
    {{ lookup('template', 'chihaya.yml') | indent(width=4, indentfirst=False )}}
---
apiVersion: v1
kind: Service
metadata:
  namespace: "{{ namespace }}"
  name: chihaya
spec:
  ports:
  - port: 6969
  selector:
    app: chihaya
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "{{ namespace }}"
  name: chihaya
spec:
  selector:
    matchLabels:
      app: chihaya
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: "{{ namespace }}"
      labels:
        app: chihaya
    spec:
      volumes:
        - name: chihaya-config
          configMap:
            name: chihaya-config
      containers:
      - image: {{ chihaya_image }}
        name: chihaya
        imagePullPolicy: "{{ image_pull_policy }}"
        args: ["--config", "/etc/chihaya.yml"]
        volumeMounts:
          - name: chihaya-config
            mountPath: /etc/chihaya.yml
            subPath: chihaya.yml
