apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  clusterIP: None
  ports:
    - port: 9200
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      hostname: elasticsearch
      containers:
        - image: {{ elasticsearch_image }}
          name: elasticsearch
          env:
            - name: "node.name"
              value: "{{ '{{ .Node.Hostname }}' }}"
            - name: "discovery.seed_hosts"
              value: "elasticsearch"
            - name: "cluster.initial_master_nodes"
              value: "elasticsearch"
            - name: "cluster.name"
              value: "tg-docker-cluster"
            - name: "bootstrap.memory_lock"
              value: "false"
            - name: "ES_JAVA_OPTS"
              value: "-Xms1g -Xmx1g"
            - name: "node.ml"
              value: "false"
            - name: "xpack.ml.enabled"
              value: "false"
            - name: "xpack.monitoring.enabled"
              value: "false"
            - name: "xpack.security.enabled"
              value: "false"
            - name: "xpack.watcher.enabled"
              value: "false"
            - name: "TAKE_FILE_OWNERSHIP"
              value: "true"
          imagePullPolicy: {{ image_pull_policy }}
