apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |
    {{ lookup('template', '../../nms_stack/nms_cli/nms_stack/roles/efk/templates/kibana.yml') | indent(width=4, indentfirst=False )}}
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  clusterIP: None
  ports:
    - port: 5601
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kibana
    spec:
      volumes:
        - name: kibana-config
          configMap:
            name: kibana-config
      containers:
        - image: {{ kibana_image }}
          name: kibana
          imagePullPolicy: "{{ image_pull_policy }}"
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
