version: '3.6'

services:
  topology_service:
    image: secure.cxl-terragraph.com:443/topology_service:latest
    restart: always
    volumes:
      - ./docker_volumes/topology_service/service_config.json:/usr/local/nano/topology_service/service_config.json
      - ./docker_volumes/tglib/config.json:/usr/local/nano/topology_service/config.json
    networks:
      - terragraph_net
    command: ["/bin/sh", "-c", "alembic upgrade head && topology_service"]
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  default_routes_service:
    image: secure.cxl-terragraph.com:443/default_routes_service:latest
    restart: always
    volumes:
      - ./docker_volumes/default_routes_service/service_config.json:/usr/local/nano/default_routes_service/service_config.json
      - ./docker_volumes/tglib/config.json:/usr/local/nano/default_routes_service/config.json
    networks:
      - terragraph_net
    command: ["/bin/sh", "-c", "alembic upgrade head && default_routes_service"]
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  cut_edge_optimizer:
      image: secure.cxl-terragraph.com:443/cut_edge_optimizer:latest
      restart: always
      volumes:
        - ./docker_volumes/cut_edge_optimizer/service_config.json:/usr/local/nano/cut_edge_optimizer/service_config.json
        - ./docker_volumes/tglib/config.json:/usr/local/nano/cut_edge_optimizer/config.json
      networks:
        - terragraph_net
      command: ["/bin/sh", "-c", "cut_edge_optimizer"]
      logging:
        driver: "json-file"
        options:
          max-size: "20m"
          max-file: "10"

networks:
  terragraph_net:
    external: true
