version: '3.4'

services:
  db:
    image: mysql
    env_file:
      - ./env/mysql.env
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    restart: always
    volumes:
      - ./mysql_init_scripts:/docker-entrypoint-initdb.d:ro
      - ./docker_volumes/mysql_db:/var/lib/mysql
    ports:
      - "3306:3306"

  db_log_cleanup:
    build:
      context: .
      dockerfile: Dockerfile.nms
    image: secure.cxl-terragraph.com:443/nms:latest
    env_file:
      - ./env/cleaner.env
      - ./env/mysql.env
      - ./env/time.env
    restart: always
    volumes:
      - ./docker_volumes/logs:/logs
    command: ["/bin/sh", "-c", "ln -sf $${TZ_FILE} /etc/localtime && until nc -z $${MYSQL_HOST} 3306; do sleep 1; done && /usr/src/service/mysql_partitioner/run"]
    depends_on:
      - db

  nms:
    build:
      context: .
      dockerfile: Dockerfile.nms
    image: secure.cxl-terragraph.com:443/nms:latest
    env_file:
      - ./env/mysql.env
      - ./env/nms.env
      - ./env/time.env
    restart: always
    ports:
      - "80:80"
    command: ["/bin/sh", "-c", "ln -sf $${TZ_FILE} /etc/localtime && until nc -z bqs 8086; do sleep 1; done && npm start"]
    depends_on:
      - db
      - bqs

  beringei_1s:
    build:
      context: .
      dockerfile: Dockerfile.beringei
    image: secure.cxl-terragraph.com:443/beringei:latest
    env_file:
      - ./env/time.env
    environment:
      - BERINGEI_HOST=beringei
      - PORT=9991
      - NAME=beringei_1s
      - INTERVAL=1
      # -buckets (Number of historical buckets to use)
      - BUCKETS=12
      # -bucket_size (Size of each bucket in seconds)
      - BUCKET_SIZE=300 # 5 minutes
      - BUCKET_FINALIZE_SEC=10
      - ALLOWED_TIMESTAMP_BEHIND=30
    cap_add:
      - SYS_NICE
    restart: always
    volumes:
      - ./docker_volumes/beringei:/data
    ports:
      - "9991:9991"
    command: ["/bin/sh", "-c", "ln -sf $${TZ_FILE} /etc/localtime && beringei/tools/beringei_configuration_generator --file_path $${NAME}.json --host_names $${HOSTNAME} --port $${PORT} && beringei/service/beringei_main -beringei_configuration_path $${NAME}.json -create_directories -sleep_between_bucket_finalization_secs $${BUCKET_FINALIZE_SEC} -allowed_timestamp_behind $${ALLOWED_TIMESTAMP_BEHIND} -bucket_size $${BUCKET_SIZE} -buckets $${BUCKETS} -data_directory=/data/$${NAME} --port $${PORT} -mintimestampdelta=$${INTERVAL} -logtostderr -v=2"]

  beringei_30s:
    build:
      context: .
      dockerfile: Dockerfile.beringei
    image: secure.cxl-terragraph.com:443/beringei:latest
    env_file:
      - ./env/time.env
    environment:
      - BERINGEI_HOST=beringei
      - PORT=9992
      - NAME=beringei_30s
      - INTERVAL=30
      - BUCKETS=48
      - BUCKET_SIZE=3600 # one hour
      - BUCKET_FINALIZE_SEC=120
      - ALLOWED_TIMESTAMP_BEHIND=120
    cap_add:
      - SYS_NICE
    restart: always
    volumes:
      - ./docker_volumes/beringei:/data
    ports:
      - "9992:9992"
    command: ["/bin/sh", "-c", "ln -sf $${TZ_FILE} /etc/localtime && beringei/tools/beringei_configuration_generator --file_path $${NAME}.json --host_names $${HOSTNAME} --port $${PORT} && beringei/service/beringei_main -beringei_configuration_path $${NAME}.json -create_directories -sleep_between_bucket_finalization_secs $${BUCKET_FINALIZE_SEC} -allowed_timestamp_behind $${ALLOWED_TIMESTAMP_BEHIND} -bucket_size $${BUCKET_SIZE} -buckets $${BUCKETS} -data_directory=/data/$${NAME} --port $${PORT} -mintimestampdelta=$${INTERVAL} -logtostderr -v=2"]

  bqs:
    build:
      context: .
      dockerfile: Dockerfile.beringei
    image: secure.cxl-terragraph.com:443/beringei:latest
    env_file:
      - ./env/bqs.env
      - ./env/mysql.env
      - ./env/time.env
    environment:
      - BERINGEI_PORT=9992
    cap_add:
      - SYS_NICE
    restart: always
    volumes:
      - ./docker_volumes/logs:/home/nms/data
    ports:
      - "8086:8086"
    command: ["/bin/sh", "-c", "ln -sf $${TZ_FILE} /etc/localtime && until nc -z db 3306; do sleep 1; done && until nc -z beringei_30s $${BERINGEI_PORT}; do sleep 1; done && beringei/tools/beringei_configuration_generator --file_path beringei.json --host_names beringei_30s --port $${BERINGEI_PORT} && beringei/tools/query_service/beringei_query_service -beringei_configuration_path beringei.json -http_port 8086 -threads $${BQS_THREADS} -writer_queue_size 500000 -mysql_url tcp://$${MYSQL_HOST}:3306 -mysql_user $${MYSQL_USER} -mysql_pass $${MYSQL_PASS} -v 2 -logtostderr"]
    depends_on:
      - db
      - beringei_30s
