version: '3.4'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./docker_volumes/cxl:/docker-entrypoint-initdb.d:ro
      - ./docker_volumes/mysql_db:/var/lib/mysql
    ports:
      - "3306:3306"

  nms:
    build:
      context: .
      dockerfile: Dockerfile.nms
    image: secure.cxl-terragraph.com:443/nms:latest
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASS=12345
      - BERINGEI_HOST=beringei
      - BQS=http://bqs:8086/query
    command: ["/bin/sh", "-c", "until nc -z bqs 8086; do sleep 1; done && npm start"]
    ports:
      - "80:80"
    depends_on:
      - db
      - bqs

  beringei_1s:
    volumes:
      - ./docker_volumes/beringei:/data
    build:
      context: .
      dockerfile: Dockerfile.beringei
    image: secure.cxl-terragraph.com:443/beringei:latest
    environment:
      - BERINGEI_HOST=beringei
      - PORT=9991
      - NAME=beringei_1s
      - INTERVAL=1
      # -buckets (Number of historical buckets to use)
      - BUCKETS=12
      # -bucket_size (Size of each bucket in seconds)
      - BUCKET_SIZE=300 # 5 minutes
      - BUCKET_FINALIZE_SEC=10
      - ALLOWED_TIMESTAMP_BEHIND=30
    cap_add:
      - SYS_NICE
    ports:
      - "9991:9991"
    command: ["/bin/sh", "-c", "beringei/tools/beringei_configuration_generator --file_path $${NAME}.json --host_names beringei --port $${PORT} && beringei/service/beringei_main -beringei_configuration_path $${NAME}.json -create_directories -sleep_between_bucket_finalization_secs $${BUCKET_FINALIZE_SEC} -allowed_timestamp_behind $${ALLOWED_TIMESTAMP_BEHIND} -bucket_size $${BUCKET_SIZE} -buckets $${BUCKETS} -data_directory=/data/$${NAME} --port $${PORT} -mintimestampdelta=$${INTERVAL} -logtostderr -v=2"]

  beringei_30s:
    volumes:
      - ./docker_volumes/beringei:/data
    build:
      context: .
      dockerfile: Dockerfile.beringei
    image: secure.cxl-terragraph.com:443/beringei:latest
    environment:
      - BERINGEI_HOST=beringei
      - PORT=9992
      - NAME=beringei_30s
      - INTERVAL=30
      - BUCKETS=48
      - BUCKET_SIZE=3600 # one hour
      - BUCKET_FINALIZE_SEC=120
      - ALLOWED_TIMESTAMP_BEHIND=30
    cap_add:
      - SYS_NICE
    ports:
      - "9992:9992"
    command: ["/bin/sh", "-c", "beringei/tools/beringei_configuration_generator --file_path $${NAME}.json --host_names beringei --port $${PORT} && beringei/service/beringei_main -beringei_configuration_path $${NAME}.json -create_directories -sleep_between_bucket_finalization_secs $${BUCKET_FINALIZE_SEC} -allowed_timestamp_behind $${ALLOWED_TIMESTAMP_BEHIND} -bucket_size $${BUCKET_SIZE} -buckets $${BUCKETS} -data_directory=/data/$${NAME} --port $${PORT} -mintimestampdelta=$${INTERVAL} -logtostderr -v=2"]

  bqs:
    build:
      context: .
      dockerfile: Dockerfile.beringei
    image: secure.cxl-terragraph.com:443/beringei:latest
    environment:
      - BERINGEI_HOST=beringei_query_service
    cap_add:
      - SYS_NICE
    ports:
      - "8086:8086"
    depends_on:
      - db
    command: ["/bin/sh", "-c", "until nc -z db 3306; do sleep 1; done && beringei/tools/beringei_configuration_generator --file_path beringei.json --host_names beringei && sleep 30 && beringei/tools/query_service/beringei_query_service -beringei_configuration_path beringei.json -http_port 8086 -threads 4 -writer_queue_size 500000 -logtostderr -v=2 -mysql_url tcp://db:3306 --mysql_pass 12345"]
