- hosts: nms
  become_user: root
  become: yes
  roles:
    - role: zaxos.docker-ce-ansible-role
  tasks:
    - name: Adding existing ubuntu user to docker group
      user: 
        name: ubuntu
        groups: docker
        append: yes

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: pip3 install docker
      pip:
        name: docker
        state: present

    - name: pip3 install docker-compose
      pip:
        name: docker-compose
        state: present

    - name: mkdir cxl
      file:
        path: cxl
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0775

    - name: copy cxl.sql
      template:
        src: cxl.sql
        dest: ./cxl/cxl.sql
        owner: ubuntu
        group: ubuntu
        mode: 0644

    - name: copy compose
      template:
        src: docker-compose.yml
        dest: ./docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: 0644

    - name: log into dockerhub
      docker_login:
        username: tgdeploy
        password: 4oRC5!oEv0s6X%F2Rsam
        email: tgdeploy18@illuminatus.org
        reauthorize: yes

    - name: run nms
      docker_service:
        project_src: .
        build: no
        state: present
        pull: yes
        stopped: no
        debug: yes
