version: '3.7'

services:
  udp_ping_client:
    image: secure.cxl-terragraph.com:443/cpp_backends:latest
    env_file:
      - {{ db_gfs_path }}/env/mysql.env
    restart: unless-stopped
    ports:
      - "31338:31338/udp"
    networks:
      - inbound
      - terragraph_net
    command: ["/bin/sh", "-c", "until nc -z db 3306; do sleep 1; done && bin/udp_ping_client -logtostderr -mysql_url tcp://$${MYSQL_HOST}:3306 -mysql_user $${MYSQL_USER} -mysql_pass $${MYSQL_PASS}"]
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

networks:
  inbound:
    external: true
  terragraph_net:
    external: true
