---
- name: create path
  file:
    path: "{{ udp_ping_client_path }}"
    state: directory
    owner: "{{ docker_user }}"
    group: docker
    mode: 0755

- name: copy docker compose
  template:
    src: docker-compose.yml
    dest: "{{ udp_ping_client_path }}"
    mode: "0644"
    owner: "{{ docker_user }}"
    group: docker
    force: yes

- name: copy service file
  template:
    src: udp_ping_client_monitor.service
    dest: /lib/systemd/system

- name: start the service
  systemd:
    name: udp_ping_client_monitor
    daemon_reload: yes
    state: started
    enabled: yes
