# There doesn't really seem to be a good way to do this aside from
# creating a separate configmap for every file...
{% set grafana_provisioning_files = [
  ('template', 'provisioning/datasources/mysql.yml'),
  ('read', 'provisioning/datasources/prometheus.yml'),
  ('read', 'provisioning/dashboards/config.yml'),
  ('read', 'dashboards/udp_pinger_dashboard.json'),
  ('read', 'dashboards/link_dashboard_prometheus.json'),
  ('read', 'dashboards/docker_monitoring.json'),
  ('read', 'dashboards/network_health.json'),
] %}
{% for lookup_type, f in grafana_provisioning_files %}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "{{ namespace }}"
  name: grafana-provisioning-{{ dns_name(f) }}
data:
  {{ basename(f) }}: |
    {{ lookup(lookup_type, f) | indent(width=4, indentfirst=False )}}
---
{% endfor %}

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "{{ namespace }}"
  name: grafana-ini-files
data:
  grafana.ini: |
    [security]
    # disable creation of admin user on first start of grafana
    disable_initial_admin_creation = false

    # default admin user, created on startup
    admin_user = admin

    # default admin password, can be changed before first start of grafana, or in profile settings
    admin_password = test

    [auth.basic]
    enabled = true