apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-service-config
data:
  service_config.json: |
    {{ lookup('template', '../../../nms_stack/nms_cli/nms_stack/roles/msa/templates/weather_service/service_config.json') | indent(width=4, indentfirst=False )}}
