apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  ports:
    - port: 8080
  selector:
    app: weather-service
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
spec:
  selector:
    matchLabels:
      app: weather-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: weather-service
    spec:
      volumes:
        - name: service-config
          configMap:
            name: weather-service-config
        - name: tglib-config
          configMap:
            name: tglib-service-config
      containers:
        - image: secure.cxl-terragraph.com:443/weather_service:stable
          name: weather-service
          command: ["weather_service"]
          envFrom:
            - configMapRef:
                name: weather-service-config
          volumeMounts:
            - name: service-config
              mountPath: /usr/local/weather_service/service_config.json
              subPath: service_config.json
            - name: tglib-config
              mountPath: /usr/local/weather_service/config.json
              subPath: config.json
      imagePullSecrets:
        - name: tg-repo-creds
