version: '3.4'

services:
  ipv6:
    image: robbertkl/ipv6nat:0.3.8
    network_mode: "host"
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro
