version: '3.4'

services:
  ipv6:
    image: secure.cxl-terragraph.com:443/migo:stable
    network_mode: "host"
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro
