---
- hosts: all
  gather_facts: yes
  tasks:
    - name: install gluster
      include_role:
        name: ansible-role-glusterfs

    - name: set ipv6 transport
      lineinfile:
        path: /etc/glusterfs/glusterd.vol
        regexp: 'transport.address-family inet6'
        line: "    option transport.address-family inet6"
      register: setip6_result

    - name: restart glusterd service
      systemd:
        state: restarted
        name: glusterd
      when: setip6_result.changed

    - name: Configure replicated gluster volume
      gluster_volume:
        state: present
        name: glusterfs
        bricks: "{{ terragraph_docker_path }}/{{ gluster_bricks }}"
        replicas: "{{ groups.all | length }}"
        cluster: "{{ hostvars.values() | map(attribute='ansible_default_ipv6') | map(attribute='address') | list }}"
        host: "{{ ansible_default_ipv6.address }}"
        force: yes
      run_once: true

    - name: Start replicated gluster volume
      gluster_volume:
        state: started
        name: glusterfs

    - name: Ensure replicated gluster volume is mounted
      mount:
        name: "{{ terragraph_docker_path }}/{{ gluster_mount }}"
        src: "{{ ansible_default_ipv6.address }}:/glusterfs"
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted

    - name: Set ownership for replicated gluster mount
      file:
        path: "{{ terragraph_docker_path }}/{{ gluster_mount }}"
        owner: "{{ docker_user }}"
        group: docker
        recurse: yes
