---
- name: Install Docker container engine
  include_tasks: pkg.yml

- name: Copy Docker engine service file
  register: change_docker
  template:
    src: "docker.service.j2"
    dest: "{{ systemd_dir }}/docker.service"
    owner: root
    group: root
    mode: 0755

- name: Copy Docker environment config file
  template: src=docker.j2 dest={{ system_env_dir }}/docker

- name: Add any insecure registries to Docker config
  when: insecure_registries is defined and insecure_registries | length > 0
  lineinfile: dest={{ system_env_dir }}/docker regexp=^INSECURE_REGISTRY= line=INSECURE_REGISTRY="{% for reg in insecure_registries %}--insecure-registry={{ reg }} {% endfor %}"

- name: Add registry to Docker config
  when: add_registry is defined and add_registry > 0
  lineinfile: dest={{ system_env_dir }}/docker regexp=^ADD_REGISTRY= line=ADD_REGISTRY="{% for reg in add_registry %}--add-registry={{ reg }} {%endfor %}"

- name: create docker daemon config path
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: "{{ docker_user }}"
    group: docker
    mode: 0755

- name: configure docker http proxy if needed
  template:
    src: docker-http-proxy.conf
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    owner: "{{ docker_user }}"
    group: docker
    mode: 0755
  when: http_proxy is defined

- name: configure docker https proxy if needed
  template:
    src: docker-https-proxy.conf
    dest: /etc/systemd/system/docker.service.d/https-proxy.conf
    owner: "{{ docker_user }}"
    group: docker
    mode: 0755
  when: https_proxy is defined

- name: Enable and check Docker service
  systemd:
    name: docker
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_docker
