# Expose the mysql deployment at mysql:3306 with no ClusterIP (so it is only
# accessible through DNS)
apiVersion: v1
kind: Service
metadata:
  name: nms
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nms
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nms
spec:
  selector:
    matchLabels:
      app: nms
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nms
    spec:
      containers:
        - image: {{ nms_image }}
          imagePullPolicy: "{{ image_pull_policy }}"
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 80
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
          envFrom:
            - configMapRef:
                name: cxl-database
            - configMapRef:
                name: time-zone
            - configMapRef:
                name: nms
          name: nms
      imagePullSecrets:
        - name: tg-repo-creds
