{{- if .Values.e2eControllerCreate }}
{{ $ctlNameDNS :=  .Values.tgnms.e2ectl.controllers.name | trim | lower | replace " " "-" | replace "_" "-" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: e2e-stats-agent-start-{{ $ctlNameDNS }}
data:
  {{- tpl ((.Files.Glob .Values.tgnms.e2ectl.configmap.statsAgent).AsConfig) . | nindent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: e2e-controller-start-{{ $ctlNameDNS }}
data:
  {{- tpl ((.Files.Glob .Values.tgnms.e2ectl.configmap.e2eCtl).AsConfig) . | nindent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: e2e-nms-aggregator-start-{{ $ctlNameDNS }}
data:
  {{- tpl ((.Files.Glob .Values.tgnms.e2ectl.configmap.startAgg).AsConfig) . | nindent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: e2e-topology-conf-{{ $ctlNameDNS }}
data:
  {{- tpl ((.Files.Glob .Values.tgnms.e2ectl.configmap.topologyConf).AsConfig) . | nindent 2 }}

---
{{- end }}
