version: '3.7'

services:
  alarms:
    image: secure.cxl-terragraph.com:443/tg-alarms:latest
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      - terragraph_net
    volumes:
      - "{{ alarms_path }}:/usr/src/java"
    command: ["-s", "PLAINTEXT://kafka:9092"]

networks:
  terragraph_net:
    external: true
