---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: "{{ namespace }}"
  name: elasticsearch-master-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/terragraph/local/elasticsearch/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "{{ namespace }}"
  name: elasticsearch-master-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: "{{ namespace }}"
  name: elasticsearch-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/terragraph/local/elasticsearch/master"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "{{ namespace }}"
  name: elasticsearch-data-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: "{{ namespace }}"
  name: tg-kibana
  labels:
    type: local
    app.kubernetes.io/instance: tg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kibana
    helm.sh/chart: kibana-6.2.0
  annotations:
    meta.helm.sh/release-name: tg
    meta.helm.sh/release-namespace: default
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/terragraph/local/kibana"
