apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: {{ zookeeper_size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: /opt/terragraph/local/zookeeper
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ 'manager-0' if single_node else 'worker-0' }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ zookeeper_size }}