apiVersion: v1
name: database
version: 0.0.1
appVersion: 5.7.30
description: Helm chart for Terragraphs mysql relational database service.
keywords:
  - mysql
  - database
  - sql
  - db
home:
icon:
sources:
maintainers:
  - name: Sam Salmi
    email: samsalmi@fb.com
engine: gotpl
