version: '3.6'

services:
  v6up:
    image: secure.cxl-terragraph.com:443/docker_v6up:stable
    env_file:
      - env/time.env
    network_mode: "host"
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    command: ["-p", "/host/proc"]
    restart: on-failure
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/proc:/host/proc"
