---

- name: Install Kubernetes packages
  include_tasks: pkg.yml

- name: Disable system swap
  shell: "swapoff -a"

- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: yes
    state: present

- name: Enable the br_netfilter module
  shell: |
    modprobe br_netfilter

    echo br_netfilter | sudo tee --append /etc/modules

- name: Set bridging sysctl parameters
  shell: |
    echo "
    # Enable bridged networks for Kubernetes
    net.bridge.bridge-nf-call-iptables=1
    net.ipv4.ip_forward=1
    net.bridge.bridge-nf-call-ip6tables=1
    net.ipv6.conf.default.forwarding=1

    # Disable swap
    vm.swappiness=0
    " | sudo tee --append /etc/sysctl.conf

    sysctl -p

- name: Create service drop-in directory
  file:
    path: /etc/systemd/system/kubelet.service.d/
    state: directory
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0755

- name: Reload kubelet daemon
  shell: "systemctl daemon-reload && systemctl restart kubelet"
